name: Deployer l'application Weather 
on:
    push:
        branches:
            - preprod
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Init project
              uses: actions/checkout@v2
            - name: JS Linter
              uses: actions/javascript-action@v1
              with:
                milliseconds: 1000
            - name: Check package version
              uses: technote-space/package-version-check-action@v1
            - name: Create JSDoc for App
              uses: brunokrauss/jsdoc-action@1
              with:
                  jsdoc-path: 'src'
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.5.6
              with:
                heroku_api_key: ${{secrets.HEROKU_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP_PREPROD}}
                heroku_email: ${{secrets.HEROKU_EMAIL}} 
