name: Deployer l'application Weather 
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Init project
              uses: actions/checkout@v2
            - name: Minify CSS
              uses: chand1012/action-css-minify@v1
              with:
                folder: 'src/css'           
            - name: JS Linter
              uses: actions/javascript-action@v1
              with:
                milliseconds: 1000
            - name: Check package version
              uses: technote-space/package-version-check-action@v1
            - name: Checking for broken link in prod
              uses: ScholliYT/Broken-Links-Crawler-Action@v2.1.1
              with:
                website_url: 'https://devops-weather-app-prod.herokuapp.com/'
                verbose: 'true'
                max_retry_time: 30
                max_retries: 5
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.5.6
              with:
                heroku_api_key: ${{secrets.HEROKU_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP}}
                heroku_email: ${{secrets.HEROKU_EMAIL}} 
